const express=require('express'),Database=require('better-sqlite3'),crypto=require('crypto'),path=require('path'),fs=require('fs');
const DBP=process.env.DB_PATH||path.join(__dirname,'data','daily.db');
fs.mkdirSync(path.dirname(DBP),{recursive:true});
const db=new Database(DBP);db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,data TEXT,status TEXT DEFAULT 'در انتظار',at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reservations(id INTEGER PRIMARY KEY AUTOINCREMENT,data TEXT,at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,stars INTEGER,text TEXT,at TEXT DEFAULT CURRENT_TIMESTAMP);`);
if(!db.prepare('SELECT 1 FROM reviews').get()){const i=db.prepare('INSERT INTO reviews(name,stars,text) VALUES(?,?,?)');
i.run('سارا',5,'بهترین کاپوچینوی شهر! فضای کافه عالیه.');i.run('محمد',4,'کیک شکلاتی فوق‌العاده بود.')}
const AU=process.env.ADMIN_USER||'admin',AP=process.env.ADMIN_PASS||'1234';
const H=x=>crypto.createHash('sha256').update(String(x)).digest(),same=(a,b)=>crypto.timingSafeEqual(H(a),H(b));
const toks=new Map(),hits=new Map();
setInterval(()=>{hits.clear();const n=Date.now();for(const[k,v]of toks)if(v<n)toks.delete(k)},60000).unref();
const lim=m=>(q,r,n)=>{const k=q.ip+q.path,c=(hits.get(k)||0)+1;hits.set(k,c);c>m?r.status(429).json({error:'many'}):n()};
const auth=(q,r,n)=>{const t=(q.headers.authorization||'').slice(7);(toks.get(t)||0)>Date.now()?n():r.status(401).json({error:'auth'})};
const s=(v,m)=>String(v==null?'':v).trim().slice(0,m),bad=r=>r.status(400).json({error:'bad'});
const app=express();app.set('trust proxy',1);app.use(express.json({limit:'20kb'}));
app.get('/api/reviews',(q,r)=>r.json(db.prepare('SELECT id,name n,stars s,text t FROM reviews ORDER BY id DESC LIMIT 100').all()));
app.post('/api/reviews',lim(10),(q,r)=>{const t=s(q.body.t,500),st=Math.round(+q.body.s);if(!t||!(st>=1&&st<=5))return bad(r);
db.prepare('INSERT INTO reviews(name,stars,text) VALUES(?,?,?)').run(s(q.body.n,40)||'ناشناس',st,t);r.json({ok:1})});
app.post('/api/orders',lim(15),(q,r)=>{const it=(Array.isArray(q.body.it)?q.body.it:[]).slice(0,40).map(i=>({n:s(i.n,60),c:s(i.c,30),q:Math.min(50,Math.max(1,parseInt(i.q)||1)),p:Math.max(0,+i.p||0)}));
const d={it,t:it.reduce((a,i)=>a+i.p*i.q,0),n:s(q.body.n,60),p:s(q.body.p,20),ty:s(q.body.ty,20),tb:s(q.body.tb,10)};if(!it.length||!d.n||!d.p)return bad(r);
r.json({ok:1,id:db.prepare('INSERT INTO orders(data) VALUES(?)').run(JSON.stringify(d)).lastInsertRowid})});
app.post('/api/reservations',lim(10),(q,r)=>{const d={n:s(q.body.n,60),p:s(q.body.p,20),d:s(q.body.d,12),t:s(q.body.t,6),g:s(q.body.g,3)};if(!d.n||!d.p||!d.d||!d.t)return bad(r);
db.prepare('INSERT INTO reservations(data) VALUES(?)').run(JSON.stringify(d));r.json({ok:1})});
app.post('/api/admin/login',lim(8),(q,r)=>{if(same(q.body.u,AU)&&same(q.body.p,AP)){const t=crypto.randomBytes(24).toString('hex');toks.set(t,Date.now()+12*36e5);return r.json({token:t})}r.status(401).json({error:'bad'})});
app.get('/api/admin/data',auth,(q,r)=>{const J=(sql)=>db.prepare(sql).all().map(o=>({...JSON.parse(o.data),id:o.id,s:o.status,at:o.at}));
r.json({orders:J('SELECT * FROM orders ORDER BY id DESC LIMIT 500'),res:J('SELECT * FROM reservations ORDER BY id DESC LIMIT 500'),rev:db.prepare('SELECT id,name n,stars s,text t,at FROM reviews ORDER BY id DESC LIMIT 500').all()})});
app.patch('/api/admin/orders/:id',auth,(q,r)=>{if(!['در انتظار','در حال آماده‌سازی','تحویل شد','لغو'].includes(q.body.s))return bad(r);db.prepare('UPDATE orders SET status=? WHERE id=?').run(q.body.s,+q.params.id);r.json({ok:1})});
app.delete('/api/admin/reviews/:id',auth,(q,r)=>{db.prepare('DELETE FROM reviews WHERE id=?').run(+q.params.id);r.json({ok:1})});
app.use(express.static(path.join(__dirname,'public')));
app.listen(process.env.PORT||3000,()=>console.log('The Daily Brew is running'));
